crawlserver:
    build: ./crawl_server
    # command: cover the container default CMD
    volumes:
        - /data/diffind/server/logs:/data/server/logs
        - /data/diffind/server/backup:/data/server/backup
    expose:
        - 5000

crawldb:
    image: mongo:latest
    command: mongod --smallfiles
    volumes:
        - /data/diffind/db:/data/db
    ports:
        - "27187:27017"
    expose:
        - 27017

crawlclient:
    build: ./crawl_client
    volumes:
        - /data/diffind/client/logs:/data/client/logs
        - /data/diffind/client/backup:/data/client/backup
    links:
        - crawldb
        - crawlserver