crawlserver:
    build: ./crawl_server
    # command: cover the container default CMD
    volumes:
        - /data/diffind/server:/data/server
    expose:
        - 5000

crawldb:
    image: mongo:latest
    volumes:
        - /data/diffind/db:/data/db
    ports:
        - "27187:27017"
    expose:
        - 27017

crawlclient:
    build: ./crawl_client
    volumes:
        - /data/diffind/client:/data/client
    links:
        - crawldb
        - crawlserver